package Courses

import (
	"placementCracker_api/Modals/Courses"
	"placementCracker_api/imageProcessing"
)

func GetWebAppData() []Courses.WebApp {
	data := []Courses.WebApp{
		{imageProcessing.ImageToBase64("images/courses/webapp/c1.jpg"), imageProcessing.ImageToBase64("images/courses/webapp/t1.png"), "The Complete 2022 Web Development Bootcamp by Angela Yu", "This particular course has around 40 hours of content and covers all the technologies you need as a web developer.\nIt covers HTML, CSS, JavaScript quite well, and then jumps into Bootstrap, jQuery, NodeJS, Database, SQL, Git and Github, APIs, MongoDB, Mongoose, and Back-end development work.",
			"https://www.udemy.com/course/the-complete-web-development-bootcamp/?LSNPUBID=JVFxdTr9V80&ranEAID=JVFxdTr9V80&ranMID=39197&ranSiteID=JVFxdTr9V80-.AJbcMcRHUcDvSKRW0bVEg&utm_medium=udemyads&utm_source=aff-campaign"},
		{imageProcessing.ImageToBase64("images/courses/webapp/c2.jpg"), imageProcessing.ImageToBase64("images/courses/webapp/t1.png"),
			"The Web Developer Bootcamp by Colt Steele", "This course is also unique in the way that it is structured and presented. Its not like other online courses where you just watch instructor coding.\nIts more interactive with a mix of theory, sessions, exercises, demos, and research assignments. In short, its the best course for beginners who want to learn web development from scratch.",
			"https://www.udemy.com/course/the-web-developer-bootcamp/?LSNPUBID=JVFxdTr9V80&ranEAID=JVFxdTr9V80&ranMID=39197&ranSiteID=JVFxdTr9V80-VDgMP9TtZHv2sadTG3JqNA&utm_medium=udemyads&utm_source=aff-campaign"},
		{imageProcessing.ImageToBase64("images/courses/webapp/c3.jpg"), imageProcessing.ImageToBase64("images/courses/webapp/t1.png"), "The Advanced Web Developer Bootcamp",
			"This is sort of the next part of the previous course where Colt Steele, the author, and former BootCamp instructor, will teach you advanced web development technologies like React 16, Redux, D3, ES2015, Testing, CSS Flexbox, Animations, SVG, and AJAX.",
			"https://www.udemy.com/course/the-advanced-web-developer-bootcamp/?LSNPUBID=JVFxdTr9V80&ranEAID=JVFxdTr9V80&ranMID=39197&ranSiteID=JVFxdTr9V80-Wbgy9cYz9bnxxKQFAJA6SA&utm_medium=udemyads&utm_source=aff-campaign"},
		{imageProcessing.ImageToBase64("images/courses/webapp/c4.jpg"), imageProcessing.ImageToBase64("images/courses/webapp/t1.png"), "The Complete Web Developer Course 2.0",
			"This is again an excellent hands-on web development course where you will learn key web development technologies by building websites and mobile applications using HTML, CSS, Javascript, PHP, Python, MySQL, and more.\nYou will not only learn fundamental technologies like HTML, CSS, and JavaScript, but also more advanced technologies like jQuery and Bootstrap.",
			"https://www.udemy.com/course/the-complete-web-developer-course-2/?LSNPUBID=JVFxdTr9V80&ranEAID=JVFxdTr9V80&ranMID=39197&ranSiteID=JVFxdTr9V80-A.OPvoFnakI_6eDNyhxmww&utm_medium=udemyads&utm_source=aff-campaign"},
		{imageProcessing.ImageToBase64("images/courses/webapp/c5.jpeg"), imageProcessing.ImageToBase64("images/courses/webapp/t1.png"), "The Complete JavaScript Course: Build a Real-World Project", "You will learn about coding and debugging techniques, while also covering how to organize and structure your code using modules and functions. In short, this is one of the best courses to learn JavaScript in-depth.", "https://www.udemy.com/course/the-complete-javascript-course/?LSNPUBID=JVFxdTr9V80&ranEAID=JVFxdTr9V80&ranMID=39197&ranSiteID=JVFxdTr9V80-28oOZXrRw0o3ZPVHJpsGyg&utm_medium=udemyads&utm_source=aff-campaign"},
		{imageProcessing.ImageToBase64("images/courses/webapp/c6.jpg"), imageProcessing.ImageToBase64("images/courses/webapp/t1.png"), "Angular Complete Guide", "This course will teach you how to master Angular (Angular 2+, incl. Angular 5) and build awesome, reactive web apps with the successor of Angular.js, though you dont need to know Angular 1 or Angular 2, the course starts from scratch.\nFrom setup to deployment, this course covers it all! You will learn all about Components, Directives, Services, Forms, HTTP Access, Authentication, Optimizing an Angular App with Modules and Offline Compilation, and much more.",
			"https://www.udemy.com/course/the-complete-guide-to-angular-2/?LSNPUBID=JVFxdTr9V80&ranEAID=JVFxdTr9V80&ranMID=39197&ranSiteID=JVFxdTr9V80-nnhBNMJyHg34tKyRc_dUqw&utm_medium=udemyads&utm_source=aff-campaign"},
		{imageProcessing.ImageToBase64("images/courses/webapp/c7.png"), imageProcessing.ImageToBase64("images/courses/webapp/et2.png"), "Web Application & Software Architecture 101", "This is an excellent course from Educative to learn about Web application architecture. In this course, you will learn about different architectural styles like monolith, microservices, client-server, 3-tier architecture, decentralized peer-to-peer architecture, and how requests and data move in web applications.\nYou will also learn about how to think big and think in terms of layers, performance, scalability, and high availability, which is a must for todays application.", "https://www.educative.io/courses/web-application-software-architecture-101?affiliate_id=5073518643380224"},

		{imageProcessing.ImageToBase64("images/courses/webapp/c8.jpeg"), imageProcessing.ImageToBase64("images/courses/webapp/t1.png"), "Result-Oriented Web Developer", "This is one of the best web development courses for absolute beginners. It is packed with 50+ hours of content including HTML5, CSS3, Flexbox, JavaScript, Node.js, MongoDB, etc. and it is constantly updated.\nBut what really distinguishes this course is how effectively it uses visuals and animations to explain the theory. It makes it so clear and easy to understand WHY you are doing something rather than just HOW to do it.", "https://www.udemy.com/course/result-oriented-web-developer-course/?ranMID=39197&ranEAID=JVFxdTr9V80&ranSiteID=JVFxdTr9V80-aVp7jxv5rJ0JzUWfKV0EAA&LSNPUBID=JVFxdTr9V80&utm_source=aff-campaign&utm_medium=udemyads"},
		{imageProcessing.ImageToBase64("images/courses/webapp/c9.jpg"), imageProcessing.ImageToBase64("images/courses/webapp/zt3.png"), "The Complete Web Developer in 2022: Zero to Mastery", "Here are the main things you will learn in this course:\nSkills that will allow you to apply for jobs like Web Developer, Software Developer, Front End Developer, Javascript Developer, and Full Stack Developer\nBuild 10+ real-world Web Development projects you can show off\nLearn best practices to write clean, performant, and bug-free code\nMaster modern Web Development fundamentals as well as advanced topics\nLearn React + Redux to build rich front end applications\nUse NodeJS to write server-side JavaScript\nLearn to implement user authentication\nUse Express, SQL, and PostgreSQL to create full-stack applications that scale",
			"https://zerotomastery.io/courses/coding-bootcamp/"},
	}
	return data
}
